BEGIN
 DECLARE v_count NUMBER(1) := 0;
 BEGIN
 SELECT 1
 INTO v_count
 FROM USER_TAB_COLUMNS
 WHERE table_name = 'COMPONENT_EVENT'
 AND column_name = 'TABLESPACE_DATA';
 EXCEPTION
 WHEN NO_DATA_FOUND THEN
  EXECUTE IMMEDIATE 'ALTER TABLE COMPONENT_EVENT ADD TABLESPACE_DATA VARCHAR2(50)';
  COMMIT;
 END;
 END;
/

BEGIN
 DECLARE v_count NUMBER(1) := 0;
 BEGIN
 SELECT 1
 INTO v_count
 FROM USER_TAB_COLUMNS
 WHERE table_name = 'COMPONENT_EVENT'
 AND column_name = 'TABLESPACE_INDEX';
 EXCEPTION
 WHEN NO_DATA_FOUND THEN
  EXECUTE IMMEDIATE 'ALTER TABLE COMPONENT_EVENT ADD TABLESPACE_INDEX VARCHAR2(50)';
  COMMIT;
 END;
 END;
/

COMMIT ;
