-- Create the COMPONENT_EVENT table
  
CREATE TABLE IF NOT EXISTS COMPONENT_EVENT (
  COMPONENT_EVENT_ID bigint(20) NOT NULL AUTO_INCREMENT,
  COMPONENT_CD varchar(50) NOT NULL,
  COMPONENT_DESC varchar(50) DEFAULT NULL,
  COMPONENT_EVENT varchar(30) DEFAULT NULL,
  COMPONENT_LEVEL varchar(30) DEFAULT NULL,
  EVENT_DT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CTRL_INSERT_DT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CTRL_UPDATE_DT datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (COMPONENT_EVENT_ID)
)AUTO_INCREMENT = 1;

-- Create the INSTALLED_COMPONENT view
CREATE OR REPLACE VIEW INSTALLED_COMPONENT
AS
SELECT 
    DISTINCT COMPONENT_CD, COMPONENT_LEVEL, COMPONENT_DESC 
FROM 
    COMPONENT_EVENT 
WHERE 
    COMPONENT_EVENT            NOT IN ('UNINSTALL','MIGRATE')
    AND COMPONENT_EVENT_ID NOT IN 
    ( 
    SELECT 
        E1.COMPONENT_EVENT_ID 
    FROM 
        COMPONENT_EVENT E1, 
        COMPONENT_EVENT E2 
    WHERE 
        E1.COMPONENT_EVENT     = 'INSTALL'
        AND E1.COMPONENT_CD    = E2.COMPONENT_CD 
        AND E1.COMPONENT_EVENT_ID    < E2.COMPONENT_EVENT_ID
    )


