BEGIN TRAN;

DELETE FROM COMPONENT_EVENT
      WHERE COMPONENT_CD = 'CMN';

UPDATE COMPONENT_EVENT
   SET COMPONENT_LEVEL = '15'
 WHERE COMPONENT_CD IN ('OPM', 'DBM', 'DTP', 'ARC') AND COMPONENT_LEVEL LIKE '6.5.%';


UPDATE COMPONENT_EVENT
   SET COMPONENT_LEVEL = '10'
 WHERE COMPONENT_LEVEL LIKE '6.5.%';

COMMIT ;
