	CREATE TABLE COMPONENT_EVENT 
( COMPONENT_EVENT_ID   INT NOT NULL GENERATED ALWAYS AS IDENTITY,
  COMPONENT_CD         VARCHAR(50) NOT NULL,
  COMPONENT_DESC       VARCHAR(50),
  COMPONENT_EVENT      VARCHAR(30),
  COMPONENT_LEVEL      VARCHAR(30),
  EVENT_DT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CTRL_INSERT_DT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CTRL_UPDATE_DT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
 );

CREATE  VIEW INSTALLED_COMPONENT 
    ( 
        COMPONENT_CD, 
        COMPONENT_LEVEL, 
        COMPONENT_DESC 
    ) AS 
SELECT DISTINCT 
    COMPONENT_CD, 
    COMPONENT_LEVEL, 
    COMPONENT_DESC 
FROM 
    COMPONENT_EVENT 
WHERE 
    COMPONENT_EVENT  NOT IN ('UNINSTALL','MIGRATE')
    AND COMPONENT_EVENT_ID NOT IN 
    ( 
    SELECT 
        E1.COMPONENT_EVENT_ID 
    FROM 
        COMPONENT_EVENT E1, 
        COMPONENT_EVENT E2 
    WHERE 
        E1.COMPONENT_EVENT = 'INSTALL' 
        AND E1.COMPONENT_CD = E2.COMPONENT_CD 
        AND E1.COMPONENT_EVENT_ID    < E2.COMPONENT_EVENT_ID
    );
