CREATE 
PROCEDURE WEBM_CREATE_COMPONENT_EVENT(IN useTablespace_fl CHAR(1)) 
result sets 1
language sql
    BEGIN 
        DECLARE l_sql VARCHAR(2000); 
        DECLARE CONTINUE HANDLER FOR SQLSTATE '42710' SET l_sql = NULL; 
        DECLARE CONTINUE HANDLER FOR SQLSTATE '42711' SET l_sql = NULL; 
        DECLARE CONTINUE HANDLER FOR SQLSTATE '42889' SET l_sql = NULL; 
        DECLARE CONTINUE HANDLER FOR SQLSTATE '42704' SET l_sql = NULL; 
        SET l_sql  = 'CREATE TABLE COMPONENT_EVENT (COMPONENT_EVENT_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY( START WITH 1,INCREMENT BY 1,CACHE 20),'
	             ||'COMPONENT_CD VARCHAR(50) NOT NULL,COMPONENT_DESC VARCHAR(50),'
		     ||'COMPONENT_EVENT VARCHAR(30),COMPONENT_LEVEL     VARCHAR(30),'
		     ||'TABLESPACE_DATA  VARCHAR(50),TABLESPACE_INDEX  VARCHAR(50) , '
		     ||'TABLESPACE_BLOB  VARCHAR(50),EVENT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,'
		     ||'CTRL_INSERT_DT  TIMESTAMP  NOT NULL  DEFAULT CURRENT_TIMESTAMP,'
		     ||'CTRL_UPDATE_DT  TIMESTAMP  NOT NULL  DEFAULT CURRENT_TIMESTAMP )'; 
        IF useTablespace_fl = 'Y' THEN 
            SET l_sql = l_sql ||' IN WEBMDATA INDEX IN WEBMINDX LONG IN WEBMBLOB'; 
        END IF; 
        EXECUTE IMMEDIATE l_sql; 
        SET l_sql = 'CREATE UNIQUE INDEX CMPNNTVNT_PKX ON COMPONENT_EVENT (COMPONENT_EVENT_ID)'; 
        EXECUTE IMMEDIATE l_sql; 
        SET l_sql = 'ALTER TABLE COMPONENT_EVENT ADD CONSTRAINT CMPNNTVNT_PKX PRIMARY KEY (COMPONENT_EVENT_ID)'; 
        EXECUTE IMMEDIATE l_sql; 
	SET l_sql = 'ALTER TABLE COMPONENT_EVENT ADD TABLESPACE_DATA VARCHAR(50)'; 
        EXECUTE IMMEDIATE l_sql;
	SET l_sql = 'ALTER TABLE COMPONENT_EVENT ADD TABLESPACE_INDEX VARCHAR(50)'; 
        EXECUTE IMMEDIATE l_sql;
	SET l_sql = 'ALTER TABLE COMPONENT_EVENT ADD TABLESPACE_BLOB VARCHAR(50)'; 
        EXECUTE IMMEDIATE l_sql;
        SET l_sql = 'DROP VIEW INSTALLED_COMPONENT'; 
        EXECUTE IMMEDIATE l_sql; 
        SET l_sql = 'CREATE VIEW INSTALLED_COMPONENT AS SELECT DISTINCT COMPONENT_CD, COMPONENT_LEVEL, COMPONENT_DESC,'
	            ||'TABLESPACE_DATA, TABLESPACE_INDEX, TABLESPACE_BLOB FROM COMPONENT_EVENT  '
		    ||'WHERE COMPONENT_EVENT NOT IN (''UNINSTALL'',''MIGRATE'') AND '
		    ||'COMPONENT_EVENT_ID NOT IN ( SELECT E1.COMPONENT_EVENT_ID FROM COMPONENT_EVENT E1, '
		    ||'COMPONENT_EVENT E2 WHERE E1.COMPONENT_EVENT = ''INSTALL'' AND E1.COMPONENT_CD = E2.COMPONENT_CD '
		    ||'AND E1.COMPONENT_EVENT_ID < E2.COMPONENT_EVENT_ID )'; 
        EXECUTE IMMEDIATE l_sql; 
    END 